### ISSUE TITLE
Worlds can be opened with two app instances

### ISSUE THREAD

**Issue by LFF5644** [L3P3/minicraft#22]
wenn ich das spiel 2 mal geöffnet habe werden die spiel stände nicht correct gespeichert

**Comment by L3P3** [comment]
Das wird schwierig zu machen. Wie ist etwa zu erkennen, ob eine Welt gerade geöffnet ist oder ob Minicraft nur nicht richtig beendet wurde und das immer noch als geöffnet markiert ist? :thinking: Also ja, das Problem muss ich lösen, aber es ist kompliziert und deswegen brauche ich so lange!

**Comment by L3P3** [comment]
Ja, klar. Aber siehe oben. Nicht immer wird die Funktion vorm Beenden ausgeführt (Absturz, Kack-Browser, ...) und dann wäre der Eintrag dass das geöffnet ist noch drin!

**Comment by LFF5644** [comment]
wo ist das problem da ist dann einfache eine meldung: `"Instanz noch geöffnet oder wurde nicht richtig geöffnet möchtest du fortfaren?"` das kommt dann in ein `confirm` rein und bei den cancel button wird dann `history.back()` aufgerufen

**Comment by LFF5644** [comment]
ah mir ist noch was eingefallen:

wenn man eine welt öffnet wird in eine localStorage worldOpenDate oder so `Date.now()` rein gespeichert und das wird jede minute gemacht!

beim laden wird dann geguckt wenn welt geöffnet ob diese diese zeit länger her ist als 2 min wenn ja wird das ignorirt und andernfals wird ein confirm angezeigt

**Comment by L3P3** [comment]
Genau das habe ich mir auch ursprünglich überlegt. Finde nur dieses `confirm` irgendwie unschön, aber notfalls mache ich das so! `lff.smart=true;` :slightly_smiling_face:

**Comment by LFF5644** [comment]
aber nim den default 48s

**Comment by LFF5644** [comment]
oder mach so einen regler in die einstellungen von 5s bis 5 min

**Comment by L3P3** [comment]
Könnte ich machen... Nehme aber erstmal eine feste Zahl und später will ich eh die Menüs richtig machen!

**Comment by LFF5644** [comment]
4 monate später es ist immernoch das gleiche menu was du "besser" machen wolltest xD

**Comment by L3P3** [comment]
Tja. Anderes ist halt wichtiger.

**Comment by L3P3** [comment]
Wurde behoben mit Broadcast.

**Comment by LFF5644** [comment]
> 4 monate später es ist immernoch das gleiche menu was du "besser" machen wolltest xD

Genau ein Jahr Später und noch das gleiche Menü...
