### ISSUE TITLE
Camera jumps up on menu

### ISSUE THREAD

**Issue by Littleclone** [L3P3/minicraft#46]
Es passiert manchmal das die Kamera wenn man ins Menü geht (Escape drückt) nach oben schaut oder das wenn man raustabt das die kamera dann wenn man wieder zurück ins Spiel geht auch nach oben geht (Selten). Dies sollte als beschreibung etwas genügen, sollten nachfragen sein bin ich bereit diese zu beantworten. (Bin noch unsicher was genau der trigger für diesen Bug ist)

**Comment by L3P3** [comment]
This only happens in chromium based browsers and is a chrome bug in my opinion, since the mousemove event happens before the pointer unlock event.

**Comment by L3P3** [comment]
Added a little workaround that should improve this a lot. Open a new issue in case this still annoys.
